# Generated by Django 3.1.1 on 2020-09-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_center_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='type_of',
            field=models.CharField(max_length=200),
        ),
    ]
