# Generated by Django 3.1.1 on 2020-09-19 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc_center_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_center_app.types')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
