# Generated by Django 3.1.1 on 2020-09-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_center_app', '0002_auto_20200921_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
