# Generated by Django 3.1.1 on 2020-09-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_center_app', '0003_bids_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='owner',
            field=models.CharField(default='p', max_length=200),
            preserve_default=False,
        ),
    ]
