# Generated by Django 3.1.1 on 2020-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_center_app', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
