# Generated by Django 3.1.1 on 2020-09-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_center_app', '0006_activity_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='type_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doc_center_app.type_of_membership'),
            preserve_default=False,
        ),
    ]
