# Generated by Django 3.1.1 on 2020-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_center_app', '0007_docs_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='number_name',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
